# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: malanchev@cmu.edu
author_name: LINCC Frameworks
create_example_module: false
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: healpix_geometry_analysis
project_license: MIT
project_name: healpix-geometry-analysis
project_organization: lincc-frameworks
python_versions:
- '3.12'
